name: bia_flutter_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  crypto: ^3.0.3
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2


flutter:
  uses-material-design: true
  fonts:
    - family: BiaIcons
      fonts:
        - asset: lib/config/fonts/BiaIcons.ttf

  assets:
    - .env
